### ISSUE TITLE
Use copy() instead of append() for large arrays 

### ISSUE THREAD

**Issue by feliixx** [alexkohler/prealloc#1]
If the array is quite large, it's more efficient to use `copy()` instead of `append()`

so for example, if `len(optionalSet) > 100` and if optionalSet is a `slice`

```go
var missing []string
for _, feature := range optionalSet {
	missing = append(missing, feature)
}
```

should become 

```go
missing := make([]string, len(optionalSet)
copy(missing, optionalSet)
```

instead of 
```go
missing := make([]string, 0, len(optionalSet))
for _, feature := range optionalSet {
	missing = append(missing, feature)
}
```

**Benchmark:**

For example, when `len(existing) = 500`, with this new test: 

```go
func BenchmarkPreallocateCopy(b *testing.B) {
	existing := make([]int64, 200, 200)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		// Preallocate our initial slice
		init := make([]int64, len(existing))
		copy(init, existing)
	}
}
```
the results clearly shows that copy is faster: 

```
BenchmarkNoPreallocate-2     	  300000	      4039 ns/op
BenchmarkPreallocate-2       	 1000000	      1664 ns/op
BenchmarkPreallocateCopy-2   	 1000000	      1303 ns/op
```

Maybe it should be mention somewhere in the README ?

**Comment by barryz** [comment]
Why `copy()` is so faster than `append()` ? @feliixx

**Comment by feliixx** [comment]
@barryz not really sure, but I when looking at the [implementation](https://github.com/golang/go/blob/master/src/runtime/slice.go#L192), we can see that basically `append()` do this : 

```go
func growslice(et *_type, old slice, cap int) slice {
  ...
  // grow the underlying array, may allocate or not 
  mallocgc()
  // add the element to the slice with a specific method depending on the element type
  memmove() | typedmemmove()
  ...
}
```
whereas `copy()` is only a single call to `memmove()`. So I guess that the difference is the cost of calling `mallocgc()` and `memmove()` or `typedmemmove()` many times

**Comment by alexkohler** [comment]
That's a good point I hadn't considered - I'll add a note in the README!

**Comment by tv42** [comment]
Your example is a bit weird, `optionalSet` is a `map[string]bool`.

**Comment by barryz** [comment]
example should be:
```golang
for _, feature := range optionalSet {
	missing = append(missing, feature)
}
```
@feliixx  😸

**Comment by feliixx** [comment]
@tv42  @barryz you're totally right, I didn't pay enough attention on the example. Of course will only work if  `optionalSet` is a slice, as in the benchmarks!
