### ISSUE TITLE
prealloc confused by ranging over a channel

### ISSUE THREAD

**Issue by y0ssar1an** [alexkohler/prealloc#13]
```go
var jobs []job
for job := range jobc {
    jobs = append(jobs, job)
}
```
In the code above, `jobc` is an unbuffered channel. I don't know the number of jobs that will be pulled from it. So I can't preallocate it.

**Comment by tyler-smith** [comment]
You should preallocate the slice with 0 length and a non-0 reasonable capacity based on your work load.

**Comment by MaerF0x0** [comment]
@tyler-smith  we cant prealloc space because it will fill with the 0 value and also append does this for us if we choose 0 capacity.

**Comment by y0ssar1an** [comment]
Channels are not slices. When you append to a slice, it doesn't block. Sending on a channel _can_ block. Blocking may be the desired behavior. There are many ways to write concurrent code, and some of those ways _require_ unbuffered channels for correctness. `prealloc` can't possibly know the algorithm we're trying to implement, so it should never recommend preallocating channels.
