### ISSUE TITLE
is preallocating array with 0 length still get benefit on performance ?

### ISSUE THREAD

**Issue by wahyudibo** [alexkohler/prealloc#17]
Hi, i have case when i need to define array that supposed to received result from database. Previously i have done this:

```
var models []Model
result := db.Where("namespace = ?", namespace).Find(&clients)
``` 
where the result length is arbitrary. When i run prealloc, it suggests me to preallocating the array so i revised the code like this

```
models := make([]Model, 0) // i put 0 since i don't know the length yet
result := db.Where("namespace = ?", namespace).Find(&clients)
``` 

So, am i doing this correctly ? is preallocating the array with zero length because the length can be arbitrary still gaining the performance benefit rather than defining it with `var`?

Thanks!

**Comment by alexkohler** [comment]
Hi @wahyudibo, would you mind linking a larger code snippet? Is the length of `models` at all tied to the length of `clients`?

**Comment by alexkohler** [comment]
Closing - feel free to reopen with more information :smile_cat:
