### ISSUE TITLE
Duplicate output lines for repeat append calls in a loop

### ISSUE THREAD

**Issue by mark-rushakoff** [alexkohler/prealloc#6]
Given this sample program:

```
package main

import "fmt"

func main() {
	var buf []byte

	strings := []string{"foo", "bar", "baz"}
	for i, s := range strings {
		buf = append(buf, s...)
		buf = append(buf, '\n')
	}

	fmt.Println(buf)
}
```

prealloc will output:

```
main.go:6 Consider preallocating buf
main.go:6 Consider preallocating buf
```

It appears to be outputting a line for each append in the loop, i.e. if I add one more `buf = append(buf, x)` there will be one more "main.go:6 Consider preallocating buf" line output.

There should be at most one warning regardless of multiple `append` calls.

**Comment by alexkohler** [comment]
Good find!

**Comment by alexkohler** [comment]
If anyone wants some help in picking this up, just let me know :+1:

**Comment by alexkohler** [comment]
This appears to be fixed in master.
