### ISSUE TITLE
Set exit status when suggestions are found

### ISSUE THREAD

**Issue by polyfloyd** [alexkohler/prealloc#9]
Setting the exit status of prealloc to something other than 0 would make it possible to use in CI builds as a means of verification.

If compatibility is a concern, a flag could be used to enable this behavior. In that case, the flag would ideally be `-set_exit_status` to be consistent with `golint`.

**Comment by alexkohler** [comment]
This is a great point! I actually was not aware of golint's `-set_exit_status_flag` - I thought it always reserved non-zero exit statues for things like invalid paths, etc... Thanks for the suggestion 👍
